# Generated by Django 3.0.6 on 2020-05-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFileName', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productIDs', models.CharField(max_length=999)),
                ('productAmount', models.CharField(max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingChart',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='reviewText',
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='search',
            new_name='searchQuery',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photoID',
        ),
        migrations.AddField(
            model_name='orders',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Users'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='productID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Products'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Users'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='keywordIDs',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(max_length=999),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Users'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='productID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shoppingCartID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.ShoppingCart'),
        ),
    ]
