# Generated by Django 3.0.6 on 2020-05-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0002_auto_20200507_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='shoppingCartID',
            new_name='shoppingCart',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='productID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='productID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='userID',
            new_name='user',
        ),
    ]
