# Generated by Django 3.0.6 on 2020-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0003_auto_20200507_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mainImage',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimages',
            name='imageFileName',
            field=models.CharField(max_length=255),
        ),
    ]
