# Generated by Django 3.0.6 on 2020-05-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0004_auto_20200508_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='datetime',
            field=models.DateTimeField(default='2020-01-01 08:00:00', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewTitle',
            field=models.CharField(default='kukur', max_length=255),
            preserve_default=False,
        ),
    ]
