# Generated by Django 3.0.6 on 2020-05-10 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0009_auto_20200510_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 14, 20, 20, 607416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaptainConsole.Users'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 14, 20, 20, 608436, tzinfo=utc)),
        ),
    ]
