# Generated by Django 3.0.6 on 2020-05-10 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0012_auto_20200510_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
