# Generated by Django 3.0.6 on 2020-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0013_auto_20200510_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
