# Generated by Django 2.2.12 on 2020-05-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0015_auto_20200510_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='imageFileName',
            new_name='imageLink',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='mainImage',
            new_name='mainImageLink',
        ),
    ]
