# Generated by Django 3.0.6 on 2020-05-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0015_previouslyviewed'),
        ('CaptainConsole', '0017_auto_20200511_1743'),
    ]

    operations = [
    ]
