# Generated by Django 3.0.6 on 2020-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0018_merge_20200512_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
