# Generated by Django 2.2.12 on 2020-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0021_auto_20200513_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
