# Generated by Django 2.2.12 on 2020-05-13 15:07

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0025_auto_20200513_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
