# Generated by Django 2.2.12 on 2020-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0028_auto_20200513_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='additionalInfo',
            new_name='additionalinfo',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='orders',
            name='creditcardnumber',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='cvv',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='expirationdate',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='fullname',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='nameoncard',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='orderitems',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='zip',
            field=models.CharField(default=123, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
