# Generated by Django 2.2.12 on 2020-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0029_auto_20200513_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
