# Generated by Django 2.2.12 on 2020-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0030_auto_20200513_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
