# Generated by Django 2.2.12 on 2020-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0031_auto_20200513_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cvv',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderitems',
            field=models.ManyToManyField(to='CaptainConsole.Products'),
        ),
    ]
