# Generated by Django 3.0.6 on 2020-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0034_auto_20200514_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
