# Generated by Django 3.0.6 on 2020-05-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0035_auto_20200515_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
