# Generated by Django 2.2.12 on 2020-05-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaptainConsole', '0036_auto_20200515_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAndShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoncard', models.CharField(max_length=50)),
                ('creditcardnumber', models.CharField(max_length=16)),
                ('expirationdate', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
                ('shippingcompany', models.CharField(max_length=50)),
                ('shippingoption', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='shippingcompany',
            field=models.CharField(default='dhl', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shippingoption',
            field=models.CharField(default='standard', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
